config/routes.rb
Persongroup::Application.routes.draw do
  resources :groups

  resources :people
  root 'people#index'

end

app/models/group.rb
class Group < ActiveRecord::Base

    validates :name, presence: true
    validates :name, uniqueness: true

    has_many :people, dependent: :destroy

end

app/models/person.rb
class Person < ActiveRecord::Base
    
    validates :name,:phone,:address,:group_id, presence: true

    validates :phone, format: { with: /\A\+?[0-9\-]{8,13}\z/, message: "Please enter a valid phone number" }

    belongs_to :group

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    
    
    def index
        @people=Person.all
        if(params.key?(:search) and !params[:search].empty?) 
            search=params[:search]
            search='%'+search+'%'
            @people=Person.where("name LIKE ? or phone LIKE ? or address LIKE ? ",search,search,search)
        end

        @people=@people.page(params[:page]).per(3)
    end

    def create
        @person=Person.new(person_params)
        if @person.save
            redirect_to person_path(@person.id) 
        else
            render :new
        end
    end

    def new
        @person=Person.new
    end

    def edit
        @person=Person.find(params[:id])
    end

    def show
        @person=Person.find(params[:id])
    end

    def update
        @person=Person.find(params[:id])
        @person.update(person_params) and redirect_to person_path(@person) and return
        render :edit
    end

    def destroy
        @person=Person.find(params[:id])
        @person.destroy
        redirect_to people_path
    end

    private
        def person_params
            params.require(:person).permit(:name,:address,:phone,:group_id)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>

<div class="form-horizontal">
    <div class="form-group">
        <%= f.label :name, class: 'form-label col-md-4'   %>
        <div class="col-md-8">
            <% @group.errors[:name].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :description, class: 'form-label col-md-4'   %>
        <div class="col-md-8">
            <% @group.errors[:description].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.text_field :description , class: 'form-control'%>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-4 col-md-8"><%= f.submit class: 'btn btn-primary' %></div>
    </div>
</div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group, class:'btn btn-default' %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= link_to 'Show', group, class:'btn btn-default' %>
        <%= link_to 'Edit', edit_group_path(group) , class:'btn btn-default'%>
        <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path , class:'btn btn-primary'%>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<dl>
<dt>Name:</dt>
<dd><%=@group.name%></dd>
<dt>Description:</dt>
<dd><%=@group.description%></dd>
<dt>People:</dt>
<dd>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @group.people.each do |p| %>
        <tr>
            <td><%=p.name%></td>
            <td><%=p.address%></td>
            <td><%=p.phone%></td>
            <td>
                <a class="btn btn-default" href="<%= url_for(p) %>"><i class="glyphicon glyphicon-ok"></i></a>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

</dd>
</dl>

<%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-default' %> 
<%= link_to 'Delete', group_path(@group), method:'DELETE' , confirm: 'Are you sure?' , class: 'btn btn-danger' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Persongroup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">People Group</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<%=people_path%>">People</a></li>
                    <li><a href="<%=groups_path%>">Groups</a></li>
                </ul>
            </div>
        </div>

    </div><!-- /.container-fluid -->

</nav>

    <div class="container">
        <%= yield %>
    </div>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
<div class="form-horizontal">
    <div class="form-group">
        <%= f.label :name, class: 'form-label col-md-4' %>
        <div class="col-md-8">
            <% @person.errors[:name].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :address, class: 'form-label col-md-4'  %>
        <div class="col-md-8">
            <% @person.errors[:address].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.text_field :address, class: 'form-control'%>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :phone, class: 'form-label col-md-4'  %>
        <div class="col-md-8">
            <% @person.errors[:phone].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.text_field :phone, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :group, class: 'form-label col-md-4'  %>
        <div class="col-md-8">
            <% @person.errors[:group].each { |s| %>
            <%= s %><br />
            <% } %>
            <%= f.collection_select :group_id, Group.all, :id, :name, {}, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-4 col-md-8"><%= f.submit :submit , class: 'btn btn-primary' %></div>
    </div>
</div>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= render 'form' %>

app/views/people/index.html.erb
<h1>People Index</h1>

<div class="row">
    <div class="col-md-3">
        <%= form_tag people_path, method: "get" do %>
        <%= text_field_tag(:search, params[:search],class: 'form-control') %>
        <% end %>
    </div>
</div>
<br />

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th style="width:10%;"></th>
        </tr>
    </thead>
    <tbody>
        <% @people.each do |p| %>
        <tr>
            <td><%=p.name%></td>
            <td><%=p.address%></td>
            <td><%=p.phone%></td>
            <td class="text-center">
                <a class="btn btn-default" href="<%= url_for(p) %>">View</a>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= paginate @people %>
<a class="btn btn-primary pull-right" href="<%=new_person_path%>">New</a>

app/views/people/new.html.erb
<h1>New People</h1>

<%= render 'form' %>

app/views/people/show.html.erb
<h1>Person Detail</h1>

<dl>
    <dt>Name:</dt>
    <dd><%=@person.name%></dd>
    <dt>Address:</dt>
    <dd><%=@person.address%></dd>
    <dt>Phone:</dt>
    <dd><%=@person.phone%></dd>
    <dt>Group:</dt>
    <dd>
        <% if(@person.group.nil?) %>
        No group selected
        <% else %>
        <%= link_to @person.group.name, group_path(@person.group) %>
        <% end %>
    </dd>
</dl>

    <a class="btn btn-default" href="<%=edit_person_path(@person)%>">Edit</a> <a class="btn btn-default" href="<%=person_path(@person)%>" data-method="DELETE" data-confirm="Are you sure?">Delete</a>